#+title: Homework 
#+author: Yu Zhao
#+OPTIONS: date
# We need fancyhdr to generate the header and amsmath to typeset certain math symbols
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{amsmath,amsthm,amssymb}
#+LATEX_HEADER: \usepackage{tikz}
# Don't export table of contents. 
#+OPTIONS: toc:nil
# Don't make a title page.
# Don't do automatic section numbering, as they will not correspond with problem
#    numbers from the book
#+LATEX: \setcounter{secnumdepth}{-1}

1. Consider the map $f$ from $C$ to $C^{2}$ by $f(t)=(t^{3}, t^{5})$,
   which is obviously a bijective map. In fact if $t_{1}\neq t_{2}$
   but $f(t_{1})=f(t_{2})$, then we have $t_{1}$ and $t_{2}$ are all
   nonzero, and induce that $t_{1}^{2}=t_{2}^{2}$ and hence
   $t_{1}=t_{2}$. Similarly, this map is surjective. And this map is
   continuous, hence we only need to check it is an open map.

   For $t\neq 0$, $f$ is a local isomorphism, and for $t=0$, then
   $f(B_{\epsilon})$ = $C \cap U(\epsilon^{3},\epsilon^{5})$, here $C$
   is the algebraic curve $\{(x,y)|x^{5}=y^{3}\}$ and $U(a,b)
   =\{(x,y)| |x|<a, \ |y|<b\}$.

2. Consider the action $Z/pZ$ acts on $C^{2}$ by
   $[1](z_{1},z_{2})=(e^{2\pi i/p}z_{1},e^{2\pi i q/p}z_{2})$.  with
   $q, p$ coprime with $q$. Then the quotient of the action on $S^{3}$
   is lens space $L(p,q)$. And if this quotient space is a manifold,
   it must be dimension 4. Consider the neighborhood of $0$ into an
   open subset of $R^{4}$, then we can induce a embedding of $L(p,q)$
   in to $S^{4}$, which will not exist.

   A example is that we can assume $p=2$ and $q=1$, then the lens space
   is $P=RP^{3}$, if it can be embedded into $S^{4}$. We consider the
   $Z_{2}$ cohomology. By Alexander's
   duailty theorem, we have $\widetilde{H^{0}}(S^{4}-P)=Z_{2}^{2}$, thus
   it has two connected component and we denote them $A$, $B$ to be
   there closure. Then we have $A\cap B=P$ and $A\cup B=S^{4}$, by
   Lefshetz duality and Mayer-Viectoris sequence we have
   $H_{4}(A)\oplus H_{4}(B)=H^{4}(S^{4})/P= \tilde{H}^{0}(P)=0$. 

   By the Mayer-Viectoris sequence again, we have
   $H^{1}(A)+H^{1}(B)=Z_{2}$. We assume $H^{1}(A)=0$ and
   $H^{1}(B)=Z_{2}$ generated by $b$. and hence we use the $Z/2Z$
   cohomology, and thus found $b^{3}$ generate $H^{3}(P)$. Hence the
   map from $H^{3}(P)$ to $H^{4}(S^{4})$ is a zero map. Thus we have
   the following exact sequence: $Z_{2}=H^{4}(S^{4}) \simeq H^{4}(A)
   \oplus  H^{4}(B)$ contradiction!


