# We need fancyhdr to generate the header and amsmath to typeset certain math symbols
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \newtheorem{theorem}{Theorem}
# Don't export table of contents. 
#+OPTIONS: toc:nil

# Don't make a title page.
# Don't do automatic section numbering, as they will not correspond with problem
#    numbers from the book
# Use manual numbering to match up with assigned problem numbers.
* Hilbert Scheme 
  #+LATEX: \pagestyle{fancy}
  #+LATEX: \fancyhead{}
  #+LATEX: \rhead{\textit{Your Name Here}}
  #+LATEX: \lhead{\textit{Class Name}}
  #+LATEX: \small
  
  # Use manual numbering to match up with assigned problem numbers.
  



  
Our purpose is to modulize all the closed schemes of a projective scheme . So first here we assume that   
$X=P^{n}$ is a projective scheme over $k$.

** Rough idea : the information of quotient ring

   The key point to moduli something is to find key information which can
   seperate different objects. For closed subschemes, a basic information
   is Hilbert polynomials, from this we can seperate quotient schemes
   which are different under flat morphisms.

   Another information is considering the map $\phi_{F}$ from
   $H^{0}(\mathcal{O}(n))$  to $H^{0}(\mathcal{F}(n))$, which is an
   surjective map for large $n$. Hence the kernel of this map form a subspace of
   particular dimension. And by the fact that the ideal sheaf is
   genated by high dimension global sections we have the fact that
   all those maps can seperate the different ideals. But this is not
   enough for modulize since there are infinite informations about
   it. To catch the finite information we want that
   $H^{0}(X,\mathcal{F}(n))$ are generated by
   $H^{0}(X,\mathcal{F}(m))$ for some invariant $m$. The condition we 
   need here is a kind of regularity:

   
   #+BEGIN_THEOREM
sdf
   
   #+END_THEOREM

